rm(list=ls())
data<-read.csv('household_power_consumption.txt',head=T,sep=";",na.string="?",stringsAsFactor=FALSE)
data_sub<-subset(data,Date%in%c('1/2/2007','2/2/2007'))
data_sub$Date <- as.Date(data_sub$Date, format="%d/%m/%Y")
data_sub<-transform(data_sub, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(data_sub$timestamp,data_sub$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(data_sub$timestamp,data_sub$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(data_sub$timestamp,data_sub$Sub_metering_1,type="l",xlab="", ylab="Energy sub metering")
lines(data_sub$timestamp,data_sub$Sub_metering_2,col="red")
lines(data_sub$timestamp,data_sub$Sub_metering_3,col="red")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
plot(data_sub$timestamp,data_sub$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()