rm(list=ls())
data<-read.csv('household_power_consumption.txt',head=T,sep=";",na.string="?",stringsAsFactor=FALSE)
data_sub<-subset(data,Date%in%c('1/2/2007','2/2/2007'))
data_sub$Date <- as.Date(data_sub$Date, format="%d/%m/%Y")
data_sub<-transform(data_sub, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
png("plot2.png")
plot(data_sub$timestamp,data_sub$Global_active_power,type="l",xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
